name: Build ARM64 DLL

on:
  push:
    branches: [ "rust" ]
  workflow_dispatch: # Allows you to trigger the build manually

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-pc-windows-msvc

      # The --workspace flag ensures the 'dll' sub-project is compiled
      - name: Build ARM64 target
        run: cargo build --release --workspace --target aarch64-pc-windows-msvc

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VirtualDesktopAccessor-ARM64
          # Grab any DLL outputted into the release folder
          path: target/aarch64-pc-windows-msvc/release/*.dll
